fetchai/agents-tac

README.md
This PR:
- corrects main readme so that developers only install those dependencies required at each step.
=> Updates main readme to correctly reflect dependencies

Pipfile, Pipfile.lock, tac/gui/dashboards/agent.py, tac/gui/dashboards/base.py, tac/gui/dashboards/controller.py
This PR aims to fix some issues related to the GUI modules. The changes have been commented inline.
=> Fx misc issues in gui modules.

simulation/v1/tac_agent_spawner.py, tac/agents/v1/examples/baseline.py
Fix code style in `simulation/v1/tac_agent_spawner.py` and `tac/agents/v1/examples/baseline.py` modules.
=> Fix code style

tac/__version__.py, tac/agents/v1/base/lock_manager.py, tac/agents/v1/base/negotiation_behaviours.py, tac/gui/dashboards/agent.py, tac/gui/dashboards/controller.py, tac/helpers/misc.py, tac/platform/controller.py, tac/platform/game.py, tac/platform/protocol.py, tac/platform/stats.py, tests/test_game.py, tests/test_protocol.py
This PR removes the class `GameTransaction` which was introduced to aid modularisation but ends up causing confusion with the `Transaction` class and does not achieve its aim of modularisation anyway.
The `Transaction` class is now used throughout. As a result it had to be extended with a few methods previously available only in `GameTransaction`, notably `to_dict` and `from_dict`. Since `Transaction` also contains the crypto module this has caused for slight bloat in two or three instances as a crypto object needs to be generated with no direct use. However, this downside is outweighed by the fact that now the code is much easier to read as there is one `Transaction` class used throughout.
One of the params of the `Transaction` class was changed from the ambiguous `buyer` to the explicit …
=> Removes duplicate GameTransaction class to avoid confusion with Transaction.

CONTRIBUTING.rst, HISTORY.rst, MANIFEST.in, tac/__version__.py
Updates meta information
N/A
N/A
=> Updates meta information.

sandbox/run_iterated_games.py
The PR fixes a bug due to a recent change in the Game.get_scores() method, which returns a mapping from agent pbk to scores rather than a list of scores.
N/A
N/A
=> fix issue in computation of final ranking in the iterated games script.

tac/agents/v1/mail.py
The Mailbox now automatically tries to reconnect to the OEF when a `ConnectionError` occurs.
fixes #302 & #311 
None.
=> add automatic reconnection to OEF.

tac/agents/v1/base/game_instance.py, tac/agents/v1/examples/strategy.py
This PR introduces a check for positive price in agent strategy and agent game instance `get_proposal` methods.
It fixes #320 
n/a
=> Adds checks for positive price to strategy and get proposal methods

sandbox/playground.py
This creates a simple script to interact with an agent.
This addresses #314 
N/A
=> Adds a simple script to launch two agents and interact with them.

LICENSE
Fix the copyright notice in the `LICENSE` file.
None.
- [] I have added tests that prove my fix is effective or that my feature works
None.
=> Fix copyright notice in LICENSE file.

tac/gui/panel/forms/agent.py, tac/gui/panel/static/main.css, tac/gui/panel/templates/base.html, tac/gui/panel/templates/includes/navbar.html, tac/gui/panel/templates/panel.html
- Add navigation bar. 
- Add footer with copyright notice. 
- Add custom CSS file.
- Reduce indentation of HTML code.
None.
None.
=> Refine GUI.

tac/platform/controller/controller_agent.py, tests/common.py, tests/conftest.py, tests/test_agent/test_agent_state.py, tests/test_agent/test_misc.py, tests/test_controller.py, tests/test_simulation.py
Fixes broken tests and adds new ones.
Tests
None
=> Fixes all but one test

Pipfile, Pipfile.lock, scripts/launch_alt.py, scripts/stack_tracer.py, tests/test_simulation.py
This PR adds a basic script to capture stack traces.
If addresses #295 
More needs to be done to make debugging easier. The current stack tracer is not that helpful.
=> Add stacktracer, fixes #295

Pipfile, Pipfile.lock, tac/platform/oef_health_check.py
Bump OEF SDK version to 0.6.4.
None.
None.
=> Bump OEF SDK version to 0.6.4

docker-agent-image/Dockerfile, docker-agent-image/README.md, docker-agent-image/docker-env.sh, docker-agent-image/scripts
This PR aims to add a Docker image based on [`python:3.7-alpine`](https://github.com/jfloff/alpine-python), more lightweight than the default Python Docker image.
Fixes #309 
None.
=> Lightweight Docker image for agent execution.

templates/v1/advanced.py, templates/v1/basic.py
In the `templates/v1/basic.py` and `templates/v1/advanced.py`, forward correctly the arguments related to the VIsdom server.
None.
None.
=> Fix Visdom arguments forwarding to agent templates.

Pipfile, Pipfile.lock, docker-agent-image/Dockerfile
This bumps the version of the aea package used to 0.1.1.
-
-
=> Bump to aea version 0.1.1

HISTORY.rst, Pipfile, Pipfile.lock, tac/__version__.py
=> Bumps the oef SDK version and the framework version.

mypy.ini, tox.ini
Fix failing Jenkins tests.
-
-
=> Update tox.ini to fix failing tests

HISTORY.rst, Makefile, Pipfile, Pipfile.lock, sandbox/oef_healthcheck.py, tac/__version__.py, tac/agents/controller/agent.py, tac/agents/controller/base/handlers.py, tac/agents/participant/v1/agent.py, tac/agents/participant/v1/base/dialogues.py, tac/agents/participant/v1/base/game_instance.py, tac/agents/participant/v1/base/helpers.py, tac/agents/participant/v1/base/states.py, tac/agents/participant/v1/base/stats_manager.py, tac/agents/participant/v2/agent.py, templates/v1/advanced.py, templates/v1/expert.py, tests/common.py, tests/test_agent/test_agent_state.py, tests/test_agent/test_misc.py, tests/test_mail.py
Bumps to new aea version 0.1.2. Bumps version to 0.1.5. Fixes.
-
-
=> Bumps to new aea version 0.1.2 and fixes

Pipfile.lock, README.md, setup.py
Fixed issue with aea not installing and recreared PipFile.lock. Also improved grammar of readme file so it is clearer. 
-
-
=> fixed issue with aea no installing and recreared PipFile.lock

Pipfile, Pipfile.lock, README.md
This PR updates the readme to include the now relevant information and adds `docker` and `docker-compose` as dependencies.
-
-
=> Update readme and dependencies

HISTORY.rst, tac/__version__.py
Prepares develop for 0.1.6
-
-
=> Prepare version bump to 0.1.6

.github/pull_request_template.md, HISTORY.rst, tac/__version__.py
Prepare develop for 0.1.7.
-
-
=> Prepare tac for release 0.1.7

.github/workflows/workflow.yaml, sandbox/.env, sandbox/docker-compose.yml, tac/agents/controller/agent.py, tac/agents/participant/v1/agent.py, tac/agents/participant/v1/base/stats_manager.py, tac/gui/launcher/forms/agent.py, tac/gui/launcher/forms/sandbox.py, tac/platform/shared_sim_status.py, tests/conftest.py, tox.ini
Make continuous integration work again.
n/a
n/a
=> Update continuous integration

.github/dependabot.yaml, .github/pull_request_template.md, .github/workflows/workflow.yaml, CONTRIBUTING.md, README.md, docs/sections/develop_agent.rst, templates/README.md
=> Change references of master to main

HISTORY.md, tac/__version__.py
=> Bump version to 0.1.9
